# Generated by Django 2.1.4 on 2018-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181213_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'img/django-actor-big.jpg' %}", upload_to='', verbose_name='IMAGE'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, default="{% static 'img/django-actor-big.jpg' %}", upload_to='', verbose_name='Image File'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Image Type'),
        ),
    ]
