# Generated by Django 2.1.4 on 2018-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181213_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Image File'),
        ),
    ]
