# Generated by Django 2.1.4 on 2018-12-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181213_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
    ]
